### ISSUE TITLE
How manipulate res.locals object in request?

### ISSUE THREAD

**Issue by frknbasaran** [baugarten/node-restful#112]
I want replace my date properties with momentJs. 

When i try like below;

```javascript
    var QuestionResource = app.user = restful.model('Question', questionSchema)
            .methods(['get', 'post', 'put', 'delete']);
    
        QuestionResource
            .after('get', function(req, res, next) {
                res.locals.bundle.forEach(function(question) {
                   res.locals.bundle[res.locals.bundle.indexOf(question)].created_at = moment(question.created_at).fromNow()
                })
                next()
            })
```
Response data not changed. Why? How can do this?

Thanks in advance.

**Comment by baugarten** [comment]
Yeah, you're right. Looking into this, it looks like it's because the models that are returned are not plain objects, but an instance of a mongoose object.

There are two ways to do this and I can't tell which is better.

In your post processing, you can manually call `toObject()`

```js
res.locals.bundle.forEach(function(question, idx, questions) {
  questions[idx] = question.toObject();
  questions[idx].created_at = moment(question.created_at).fromNow()
})
```

I tested this locally and it works, but is not intuitive. The alternative is to change the format of `res.locals.bundle` to use plain JS objects by default, but then you wouldn't be able to do other fancy things on them.

**Comment by frknbasaran** [comment]
It's work! Thank you my friend.
